services:
  app:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    ports:
      - "8001:8000"
    env_file:
      - .env
    volumes:
      - .:/home/vscode
    working_dir: /home/vscode
    user: vscode
    command: >
      sh -c "pip install -r requirements.txt &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
